config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :questions do
    resources :answers
  end
  
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user) # -> 這裏就是current_user
    if user.admin?
        can :manage, :all

    else   
        can :update, Question do |question|
            question.user == user  
        end     
        #以上是說 如果 （ question.user == user  ）, 就 can update Question
        

        can :destroy, Question do |question|
            question.user == user  
        end 

        can :destroy, Answer do |answer|
            answer.user == user  
        end   

        can :create, Question
        can :create, Answer

    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@question = Question.find(params[:question_id])
		#找到指定的Question
		@answer = @question.answers.build(answers_params)
		#會用answers_params建立一個 Answer的record 並且對應到@question
		@answer.user = current_user
		#設定answer user的value
		@answer.save
		redirect_to questions_path

	end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id]).destroy
		redirect_to questions_path
	end

	private

		def answers_params
			params.require(:answer).permit(:content)
		end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception| 
    redirect_to questions_path, :alert => exception.message
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to questions_path
  	end

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :check_login

  # GET /questions
  # GET /questions.json
  def index
    @questions = @paginate = Question.paginate(:page => params[:page], :per_page => 10)   

    #@posts = Post.
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    authorize! :update, @question
  end

  # POST /questions
  # POST /questions.json
  def create
    user = current_user
    #@question = Question.new(question_params)
    @question = user.questions.build(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content)
    end

    def check_login
      if !current_user
        redirect_to new_user_session_path
      end
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
  <p> 
	 <%= answer.content %> 
  </p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseCancancan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>

  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>



  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>
	<div class = "container-fluid">

	<% if user_signed_in? %>
		Welcome, <%= current_user.email %>
		<%#= link_to "Log out", destroy_user_session_path%>
		<%= link_to "log out", destroy_user_session_path, :method => 'delete' %>
	<% else %>
		<%= link_to "Log In", new_user_session_path%>

	<% end %> 
	<br>
	<%= flash[:alert] %>

<%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions page</h1>


    <% if @paginate %>
      <%= will_paginate @paginate %>
    <% end %>
    

    <% @questions.each_with_index do |question, index| %>
    <div class="question">
      
       <h2>#<%= index+1 %> <%= question.content %> </h2>
        <%= time_ago_in_words(question.created_at) %> ago by
         <em> 
          <%= question.user.email %>
        </em>
        <br>

        <% if can? :update, question %>
        <%= link_to 'Edit', edit_question_path(question) ,class: "btn btn-primary"%>
        <% end %>

         <% if can? :destroy, question %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>

        <% if question.answers.any? %>
          <h4>Answers</h4>
          <% question.answers.each do |answer| %>
          <p> 
             <%= answer.content %> 
          <% if can? :destroy, answer %>
          <%= link_to "Delete Ans",  question_answer_path(answer.question , answer), method: :delete , class: "btn btn-danger btn-xs" %>
          <% end %>
          <% end %> 
          </p>

        <% else %> 
        <br>
           No answer now!
        <% end %>

        <br>
        <p>Add Answers</p>
        <%= form_for([question,question.answers.build]) do |f| %>
          <%= f.text_area :content %>
          <%= submit_tag "Add" %>
          <br>

          <% end %>

     </div>
    <% end %>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>